#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

set -e

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

[ -d "$HIGHORDERFIT_SRC" ] || {
    echo "Error: HIGHORDERFIT_SRC directory does not exist"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

wmake -j -a src
wmake -j test
testHighOrderFit
