/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2017 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Class
    Foam::highOrderFit::uniformMultipliers

Description
    Gives equal weight to every stencil cell in the least squares fit.

SourceFiles
    uniformMultipliers.C

\*---------------------------------------------------------------------------*/

#ifndef uniformMultipliers_H
#define uniformMultipliers_H

#include "multipliers.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace highOrderFit
{

/*---------------------------------------------------------------------------*\
                         Class uniformMultipliers Declaration
\*---------------------------------------------------------------------------*/

class uniformMultipliers
:
    public multipliers
{

    // Private Member Functions

        //- Disallow default bitwise copy construct
        uniformMultipliers(const uniformMultipliers&);

        //- Disallow default bitwise assignment
        void operator=(const uniformMultipliers&);


public:

    //- Runtime type information
    TypeName("uniformMultipliers");

    // Constructors

        uniformMultipliers();


    //- Destructor
    ~uniformMultipliers();


    // Member Functions

        void calculate(const stencil& stencil, scalarList& m) const;

};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace highOrderFit

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
